version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: eval $(docker-machine env default)
      - run: npm test
      - store_test_results:
          path: /tmp/test-reports
